/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
//import com.google.gson.Gson;
//import com.google.gson.GsonBuilder;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;



public class App {


    public static void main(String[] args) throws IOException {

      ArrayList<quote> quotes = jsonParser();
      int Random = new Random().nextInt(quotes.size());
      System.out.println(quotes.get(Random));


    }

    public static ArrayList<quote> jsonParser() throws IOException {
        BufferedReader reader = new BufferedReader(new FileReader("app/src/main/resources/qutes.json"));
        GsonBuilder Builder = new GsonBuilder();
        Gson gson = Builder.create();
        return gson.fromJson(reader, new TypeToken<ArrayList<quote>>() {}.getType());

    }

}
